export const Logo = {
	logo: require("../Assets/img/Logo.png"),
};

export const Img = {
	footer_img: require("../Assets/img/office.png"),
	home_banner_img: require("../Assets/img/Home_BG.png"),
	our_services_1: require("../Assets/img/our_services_1.png"),
	our_services_2: require("../Assets/img/our_services_2.png"),
	our_services_3: require("../Assets/img/our_services_3.png"),
	our_services_4: require("../Assets/img/our_services_4.png"),
	c_success_1: require("../Assets/img/Success_1.png"),
	c_success_2: require("../Assets/img/Success_2.png"),
	c_success_3: require("../Assets/img/Success_3.png"),
	c_success_4: require("../Assets/img/Success_4.png"),
	c_success_5: require("../Assets/img/Success_5.png"),
	ourguides: require("../Assets/img/Our_Guides.png"),
	investors_1: require("../Assets/img/Investor/Investor-1.png"),
	investors_2: require("../Assets/img/Investor/Investor-2.png"),
	investors_3: require("../Assets/img/Investor/Investor-3.png"),
	investors_4: require("../Assets/img/Investor/Investor-4.png"),
	investors_5: require("../Assets/img/Investor/Investor-5.png"),
	investors_6: require("../Assets/img/Investor/Investor-6.png"),
	aboutus: require("../Assets/img/Our_Company.png"),
	team_1: require("../Assets/img/Team/Vinay Sachdeva.png"),
	team_2: require("../Assets/img/Team/Sargun Singh.png"),
	team_3: require("../Assets/img/Team/Bhavuk Arora.png"),
	team_4: require("../Assets/img/Team/Sanchit Singh.png"),
	team_5: require("../Assets/img/Team/Karan.png"),
	team_6: require("../Assets/img/Team/Isha Gupta.png"),
	team_7: require("../Assets/img/Team/Harinder Kahlon.png"),
	team_8: require("../Assets/img/Team/Sukhwinder Singh.png"),
	team_9: require("../Assets/img/Team/Umer Sheikh.png"),
	team_10: require("../Assets/img/Team/Piyush Jain.png"),
	team_11: require("../Assets/img/Team/Sultan Singh Rana.png"),
	team_12: require("../Assets/img/Team/Amandeep Kaur.png"),
	team_13: require("../Assets/img/Team/Tabinda Khan.png"),
	team_14: require("../Assets/img/Team/Simer Gill.png"),
	team_15: require("../Assets/img/Team/Victoria.png"),
	team_16: require("../Assets/img/Team/Tamanna Mudgal.png"),
	team_17: require("../Assets/img/Team/Jinal Panchal.png"),
	team_18: require("../Assets/img/Team/Mahima Maingi Kakkar.png"),
	team_19: require("../Assets/img/Team/Fatima Beramela.png"),
	team_20: require("../Assets/img/Team/Akash Panchal.png"),
	team_21: require("../Assets/img/Team/Charanjot Singh.png"),
	team_22: require("../Assets/img/Team/Rida Kashan.png"),
	team_23: require("../Assets/img/Team/Bhargav Panchal.png"),
	are_you_ready: require("../Assets/img/are-you-ready.jpg"),
	detail_visit: require("../Assets/img/detail-visit.jpg")

};

export const Icons = {
	linkedin: require("../Assets/img/Linkedin.png"),
	twitter: require("../Assets/img/Twitter.png"),
	facebook: require("../Assets/img/Facebook.png"),
	dataupdate: require("../Assets/img/Data_Update.png"),
	readmore: require("../Assets/img/read_more.png"),
	readmorewhite: require("../Assets/img/left_arrow_white.png"),
	bioarrow: require("../Assets/img/bio_arrow.png"),
	biolinkedin: require("../Assets/img/bio_linkedin.png"),
	mail: require("../Assets/img/mail.png"),
	call: require("../Assets/img/call.png"),
	canada: require("../Assets/img/canada.jpg"),
	uae: require("../Assets/img/uae.jpg"),
	india: require("../Assets/img/india.jpg"),
};

